/* Generated By:JavaCC: Do not edit this line. MultiSQLPaserTreeConstants.java Version 5.0 */
package test;

public interface MultiSQLPaserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTQUERY = 2;
  public int JJTSUFFIX = 3;
  public int JJTSFW = 4;
  public int JJTSINGLEATTSFW = 5;
  public int JJTSELECTLIST = 6;
  public int JJTSELECTITEM = 7;
  public int JJTJOINCELL = 8;
  public int JJTJOINITEMLIST = 9;
  public int JJTJOINATTRCONDITION = 10;
  public int JJTEQUCONDITION = 11;
  public int JJTJOINITEM = 12;
  public int JJTJOINEQUCONDITION = 13;
  public int JJTFUNC = 14;
  public int JJTCONDITIONS = 15;
  public int JJTCONDITION = 16;
  public int JJTACTION = 17;
  public int JJTEQUAL = 18;
  public int JJTBETWEEN = 19;
  public int JJTIN = 20;
  public int JJTHIGHER = 21;
  public int JJTLOWER = 22;
  public int JJTJOINNAME = 23;
  public int JJTATTRIBUTE = 24;
  public int JJTRELATION = 25;
  public int JJTPATTERN = 26;
  public int JJTIDENTIFIER = 27;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Query",
    "SUFFIX",
    "SFW",
    "SingleAttSFW",
    "SelectList",
    "SelectItem",
    "JoinCell",
    "JoinItemList",
    "JoinAttrCondition",
    "EquCondition",
    "JoinItem",
    "JoinEquCondition",
    "Func",
    "Conditions",
    "Condition",
    "Action",
    "Equal",
    "Between",
    "In",
    "Higher",
    "Lower",
    "Joinname",
    "Attribute",
    "Relation",
    "Pattern",
    "IDENTIFIER",
  };
}
/* JavaCC - OriginalChecksum=c9cdb82658982178ecd7733b56061d7d (do not edit this line) */
